services:
  - type: web
    name: VlaamsCore-Bot
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GUILD_ID
        sync: false
      - key: NODE_VERSION
        value: 22
      - key: RENDER_EXTERNAL_URL
        fromService:
          name: VlaamsCore-Bot
          type: web
          property: host
